server:
  port: 8892
spring:
  Application:
    name: student-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: prod
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh
